### ISSUE TITLE
Error with remotecontrolboard protocol

### ISSUE THREAD

**Issue by j-lorente** [j-lorente/TEO_push#1]
When the project is launched, the following error appears. I tried updating YARP as it says there but I already have the newest version.

![img_2052](https://cloud.githubusercontent.com/assets/16778849/12611501/1f75a068-c4ed-11e5-9198-882f980b3af0.JPG)

**Comment by j-lorente** [comment]
It's actually the robot firmware that is on 1.2.0 while you are at 1.4.0. There's two options:
1. Downgrade to a version of YARP that has a remotecontrolboard 1.2.0
2. Wait till we upgrade to 1.4.0 on the robot.

**Comment by jgvictores** [comment]
Upgraded YARP on robot, please test whenever you can.
