### ISSUE TITLE
Migrate to https://github.com/roboticslab-uc3m

### ISSUE THREAD

**Issue by jgvictores** [j-lorente/TEO_push#3]
Migrate to https://github.com/roboticslab-uc3m :smile:

**Comment by j-lorente** [comment]
What do I have to do? Fork my repo? https://help.github.com/articles/fork-a-repo/

**Comment by jgvictores** [comment]
Nope. First, accept the invite to https://github.com/orgs/roboticslab-uc3m.
Then, from your repository, go to Settings -> Transfer ownership (in Danger zone)

**Comment by j-lorente** [comment]
Done.
